# Site configuration
# 1. Files excluded from Jekyll builds
# 2. Installed Gems
# 3. Gem settings
# 4. Jekyll settings
# 5. Collections
# 6. Jekyll collections settings
# 7. Site settings
# 8. Site navigation

# 1. Files excluded from Jekyll builds
exclude:
- README.md
- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
- screenshot.png
- LICENSE
- CNAME
- Gemfile
- Gemfile.lock
- alembic-jekyll-theme.gemspec

# 2. Installed Gems
plugins:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-default-layout
- jekyll-feed
- jemoji

# 3. Gem settings
paginate: 2 # jekyll-paginate > items per page
paginate_path: blog/page:num # jekyll-paginate > blog page
jekyll-mentions: https://twitter.com # jekyll-mentions > service used when @replying
twitter:
  username: Ianpougher # jekyll-seo-tag > Owners twitter username
author: Ian Pougher # jekyll-seo-tag > default author
social: # jekyll-seo-tag > social overrides
  name: Ian pougher# jekyll-seo-tag > real name
  links:  # jekyll-seo-tag > social aliases (sameAs)
    - https://twitter.com/Ianpougher
    - https://github.com/Overheater

# 4. Jekyll settings
sass:
  style: compressed # Style compression
permalink: pretty  # Permalink style (/YYYY/MM/DD/page-name/)
excerpt_separator: <!-- more --> # Marks end of excerpt in posts
timezone: Europe/London # Timezone for blog posts and alike

# 5. Collections
collections:
  posts:
    title: Posts # Needed for Siteleaf
    output: true
    description: "Projects, Updates, and Music suggestions" # The post list page content
    feature_text: |
      ## The Blog
      Projects, Updates, and Music suggestions
    feature_image: "/assets/Splash/BlogPostCircles.png"
    
  projectlinks:
    title: Projects # Needed for Siteleaf
    output: true
    description: "My Projects" # The post list page content
    feature_text: |
      ## Project Write-ups
      Quick descriptions and links of past and present projects
    feature_image: "/assets/Splash/Hexelone.png"

# 6. Jekyll collections settings
defaults:
  -
    values:
      image: "/assets/default-social-image.png" # Default image for sharing

# 7. Site settings
encoding: utf-8 # Make sure the encoding is right
lang: en-GB # Set the site language
title: "Ian Pougher" # Site name or title, also used in jekyll-seo-tag
logo: "/assets/logo.svg" # Site logo, also used in jekyll-seo-tag
description: "The Project site of Ian Pougher" # Site description and default description, also used in jekyll-seo-tag
url: "https://Ianpougher.com" # Site url, also used in jekyll-seo-tag
baseurl: ""
#repo: ""
#email: ""
# disqus: "alembic-1" # Blog post comments, uncomment the option and set the site ID from your Disqus account
#avatarurl: "https://www.gravatar.com/avatar/6c0377abcf4da91cdd35dea4554b2a4c" # Uses avatars for favicons to get multple sites, eg Gravatar, Twitter, GitHub
# google_analytics: ''
# service_worker: false # Will turn off the service worker if set to false
css_inline: true # Will insert all styles into a single <style> block in the <head> element and remove the style <link> reference

# 8. Site navigation
navigation_header:
  Home: /
  Projects: /projects/
  Blog: /blog/


navigation_footer:
  Ian Pougher: https://Ianpougher.com

social_links: # Appears in sidebar. Set the urls then uncomment and comment out as desired
  Twitter: https://twitter.com/Ianpougher
  #LinkedIn: 
  #Google+: 
  GitHub: https://github.com/Overheater
  link: https://ianpougher.com
 # RSS: /feed.xml

sharing_links: # Appear at the bottom of single blog posts, uncomment and comment out as desired. Colours set the button colour
  #Twitter: "#0d94e7"
  #facebook: "#3B5998"
  #Google+: "#DC4E41"
  # Pinterest: "#BD081C"
  # LinkedIn: "#0077B5"
  # tumblr: "#36465D"
  # Reddit: "#FF4500"
  # Hacker News: "#ff6600"
  # Designer News: "#2D72D9"
  # Email: ""
